<?php

function cipher_menu() {
  $items['cipher'] = array(
    'title' => 'encrypt your message here',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cipher_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['cipher_success_page'] = array(
    'title' => 'ciphered',
    'page callback' => 'ciphered',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['decipher'] = array(
    'title' => 'decrypt your message here',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('decipher_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['decipher_success_page'] = array(
    'title' => 'deciphered',
    'page callback' => 'deciphered',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['decipher_failure_page'] = array(
    'title' => 'undeciphered',
    'page callback' => 'undeciphered',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function cipher_form() {
  $form['message'] = array(
    '#title' => 'message',
    '#type' => 'textfield',
    '#description' => t('type your message here'),
  );

  $form['shift'] = array(
    '#title' => 'shift',
    '#type' => 'textfield',
    '#description' => t('how far should the letters be shifted?'),
  );

  $form['direction'] = array(
    '#title' => 'direction',
    '#type' => 'textfield',
    '#description' => t('type "right" or "left"'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'cipher me'
  );

  return $form;
}

function cipher_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'cipher_form') {
    $form['#validate'][] = 'cipher_form_validate';
  }
}

function cipher_form_validate(&$form, &$form_state) {
  if($form_state['values']['direction'] != 'right' && $form_state['values']['direction'] != 'left') {
    form_set_error('direction', t('You must designate "left" or "right" as your direction.'));
  }
  if(intval($form_state['values']['shift']) < 0 || intval($form_state['values']['shift']) > 26) {
    form_set_error('shift', t('You must use a value between 0 and 26.'));
  }
  if(!intval($form_state['values']['shift'])) {
    form_set_error('shift', t('You must use an integer.'));
  }

}

function cipher_form_submit($form, &$form_state) {
  $message = strtolower($form_state['values']['message']);
  $shift = strtolower($form_state['values']['shift']);
  $direction = strtolower($form_state['values']['direction']);
  $alphabet = range('a','z');
  $alphabet = array_merge($alphabet, $alphabet, $alphabet);
  $shift = intval($shift);
  $message = str_split($message,1);
  foreach($message as $key => $val) {
    $position = array_search($val, $alphabet);
    if ($position || $position === 0) {
      if ($direction === 'right') {
        $message[$key] = $alphabet[$position + 26 + $shift];
      }
      else if ($direction === 'left') {
        $message[$key] = $alphabet[$position + 26 - $shift];
      }
    }
  }
  $word_url = 'http://randomword.setgetgo.com/get.php';
  $resp = file_get_contents($word_url);
  $message = implode($message);
  db_query("INSERT INTO cipher_keys (keyword,shift,direction) VALUES ('{$resp}', {$shift}, '{$direction}');");
  $_SESSION['keyword'] = $resp;
  $_SESSION['message'] = $message;
  $_SESSION['shift'] = $shift;
  $_SESSION['direction'] = $direction;
  $form_state['redirect'] = 'cipher_success_page';
}

function ciphered() {

  return '</h1>Your message is "'.$_SESSION['message'].'"</h1><br><h2>Your keyword is "'.$_SESSION['keyword'].'." Use this to decipher your message</h2>';
}

function decipher_form() {
  $form['message'] = array(
    '#title' => 'message',
    '#type' => 'textfield',
    '#description' => t('paste your ciphered message here'),
  );

  $form['keyword'] = array(
    '#title' => 'keyword',
    '#type' => 'textfield',
    '#description' => t('type your special keyword here'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'decipher me'
  );

  return $form;
}

function decipher_form_submit($form, &$form_state) {
  $message = strtolower($form_state['values']['message']);
  $keyword = strtolower($form_state['values']['keyword']);
  $shift;
  $direction;
  $keys = db_query("SELECT * FROM cipher_keys WHERE keyword = '{$keyword}'");
  foreach ($keys as $key) {
      if (isset($key)) {
          $shift = $key->shift;
          $direction = $key->direction;
      }

  }
  $alphabet = range('a','z');
  $alphabet = array_merge($alphabet, $alphabet, $alphabet);
  $message = str_split($message,1);
  if (!isset($shift)) {
      drupal_goto('decipher_failure_page');
  }
  foreach($message as $key => $val) {
    $position = array_search($val, $alphabet);
    if ($position || $position === 0) {
      if ($direction === 'right') {
        $message[$key] = $alphabet[$position + 26 - $shift];
      }
      else if ($direction === 'left') {
        $message[$key] = $alphabet[$position + 26 + $shift];
      }
    }
  }
  $message = implode($message);
  $_SESSION['deciphered_message'] = $message;
  $form_state['redirect'] = 'decipher_success_page';
}

function deciphered() {

  return '<h1>'.$_SESSION['deciphered_message'].'</h1>';
}

function undeciphered() {

  return "<h1>Sorry, we couldn't decipher your message. Check your keyword and try again</h1>";
}
